### ISSUE TITLE
6080端口在局域网内无法访问

### ISSUE THREAD

**Issue by WuhanSy** [dompling/DockerFiles#1]
你好,请问可以把使用教程写得详细一些吗?

**Comment by dompling** [comment]
> 你好,请问可以把使用教程写得详细一些吗?

更新了文档了。没测试过局网的，你可以把具体问题和操作方式写清楚一些。

**Comment by WuhanSy** [comment]
![IMG_0227](https://user-images.githubusercontent.com/23512897/163357106-296e16a7-dd35-4c25-9eb4-30b96357b7c1.jpeg)

使用http://192.168.0.7:6080访问,显示nginx 500错误

**Comment by WuhanSy** [comment]
![IMG_0227](https://user-images.githubusercontent.com/23512897/163357298-408f3f57-1791-4203-84b3-aa6c1588dd77.jpeg)

在ip地址192.168.0.7的机器上,访问http://192.168.0.13:6080,显示nginx 500错误

**Comment by dompling** [comment]
> ![IMG_0227](https://user-images.githubusercontent.com/23512897/163357298-408f3f57-1791-4203-84b3-aa6c1588dd77.jpeg)
> 
> 在ip地址192.168.0.7的机器上,访问[http://192.168.0.13:6080,显示nginx](http://192.168.0.13:6080,%E6%98%BE%E7%A4%BAnginx) 500错误

你的访问方式应该用 allow_ip 的配置来访问，而且得搭配本地 VPN 的分流

**Comment by WuhanSy** [comment]
谢谢,可以使用了
